-- +goose Up
-- No data yet: simplest path is drop/recreate id + fk columns

ALTER TABLE note_table DROP CONSTRAINT IF EXISTS note_table_userid_fkey;
ALTER TABLE note_table DROP CONSTRAINT IF EXISTS note_table_pkey;
ALTER TABLE user_table DROP CONSTRAINT IF EXISTS user_table_pkey;

ALTER TABLE note_table DROP COLUMN IF EXISTS userid;
ALTER TABLE note_table DROP COLUMN IF EXISTS id;
ALTER TABLE user_table DROP COLUMN IF EXISTS id;

ALTER TABLE user_table
  ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

ALTER TABLE note_table
  ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ADD COLUMN userid BIGINT NOT NULL REFERENCES user_table(id);

-- +goose Down
-- Revert bigint ids back to uuid ids

ALTER TABLE note_table DROP CONSTRAINT IF EXISTS note_table_userid_fkey;
ALTER TABLE note_table DROP CONSTRAINT IF EXISTS note_table_pkey;
ALTER TABLE user_table DROP CONSTRAINT IF EXISTS user_table_pkey;

ALTER TABLE note_table DROP COLUMN IF EXISTS userid;
ALTER TABLE note_table DROP COLUMN IF EXISTS id;
ALTER TABLE user_table DROP COLUMN IF EXISTS id;

ALTER TABLE user_table
  ADD COLUMN id UUID PRIMARY KEY DEFAULT gen_random_uuid();

ALTER TABLE note_table
  ADD COLUMN id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ADD COLUMN userid UUID NOT NULL REFERENCES user_table(id);
