// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package tutorial

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type NoteTable struct {
	CreatedDate       pgtype.Timestamp
	Title             pgtype.Text
	DescriptionOfNote pgtype.Text
	ID                int64
	Userid            int64
}

type UserTable struct {
	Username    pgtype.Text
	CreatedDate pgtype.Timestamp
	ID          int64
}
