// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package tutorial

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNote = `-- name: CreateNote :one
INSERT INTO note_table( created_date, description_of_note, userid )
VALUES (NOW(),$1,$2)
RETURNING created_date, title, description_of_note, id, userid
`

type CreateNoteParams struct {
	DescriptionOfNote pgtype.Text
	Userid            int64
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (NoteTable, error) {
	row := q.db.QueryRow(ctx, createNote, arg.DescriptionOfNote, arg.Userid)
	var i NoteTable
	err := row.Scan(
		&i.CreatedDate,
		&i.Title,
		&i.DescriptionOfNote,
		&i.ID,
		&i.Userid,
	)
	return i, err
}

const listNotesByUser = `-- name: ListNotesByUser :many
SELECT created_date, title, description_of_note, id, userid
FROM note_table
WHERE userid = $1
`

func (q *Queries) ListNotesByUser(ctx context.Context, userid int64) ([]NoteTable, error) {
	rows, err := q.db.Query(ctx, listNotesByUser, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NoteTable
	for rows.Next() {
		var i NoteTable
		if err := rows.Scan(
			&i.CreatedDate,
			&i.Title,
			&i.DescriptionOfNote,
			&i.ID,
			&i.Userid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTitle = `-- name: UpdateTitle :exec
UPDATE note_table
SET title = $2
WHERE id = $1
`

type UpdateTitleParams struct {
	ID    int64
	Title pgtype.Text
}

func (q *Queries) UpdateTitle(ctx context.Context, arg UpdateTitleParams) error {
	_, err := q.db.Exec(ctx, updateTitle, arg.ID, arg.Title)
	return err
}
