// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package tutorial

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO user_table ( username, created_date)
VALUES ( $1, NOW())
RETURNING id, username, created_date
`

type CreateUserRow struct {
	ID          int64
	Username    pgtype.Text
	CreatedDate pgtype.Timestamp
}

func (q *Queries) CreateUser(ctx context.Context, username pgtype.Text) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, username)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Username, &i.CreatedDate)
	return i, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT username, created_date, id 
FROM user_table
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]UserTable, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserTable
	for rows.Next() {
		var i UserTable
		if err := rows.Scan(&i.Username, &i.CreatedDate, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT username, created_date, id
FROM user_table
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (UserTable, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i UserTable
	err := row.Scan(&i.Username, &i.CreatedDate, &i.ID)
	return i, err
}
